### ISSUE TITLE
Step-by-step guide

### ISSUE THREAD

**Issue by Frectorius** [Thedrummonger/MMR-Tracker#10]
I'm a very noob regarding C#, and its usage on windwos.
Can you provide a ste-by-step guide on how to build the Tracker and how to use it?
What needs to be pre-installed for it to work?

**Comment by Thedrummonger** [comment]
No need to have any experience with C# or to compile anything manually, you can just download the prebuilt release here 
https://github.com/Thedrummonger/MMR-Tracker/releases/tag/V1.13
(I should note, a new update is coming out very soon which fixes some bugs with isghjs Enemizer build, but the current version works fine for the standard beta and current release)

You may also need DotNet 5.0, but this tracker uses the same version of DotNet as the Randomizer, so if you can run the Randomizer you should have everything you need to run this.

As for usage, when you first launch the tracker you will be prompted to see "First time use information" which will display a guide detailing basic usage; but I'll write the short version here as well.

1. Click "File -> New" and select the Logic file used to create your randomizer seed. If you used the default Casual or Glitched Logic, select "File -> Presets -> MMR Casual/MMR Glitched"

2. Click "Tools -> Import Spoiler Log" to import your HTML spoiler log into the tracker. This will preset each location with the proper randomized item as well as apply all relevant settings (Junk items, Progressive Items, etc..). 

3. Your done! From here using the tracker is simple, the "Available Locations" list will display all checks that are logically available to you based on the items you have, just double click a location to mark it as checked and obtain the item. If you want to "mark" an item such as if you see it in a shop and know it's there but can't obtain it yet; select (single click) the item in the list and click the "Mark item" button (or click the list entry with your middle mouse button assuming you left that setting default).

The tracker can be used without a spoiler log if you don't have access to one, but it is highly recommended if you do. If you just want to import settings and not Item data select "Options -> Logic Options -> Edit Randomization Options" and click "Load MMR Settings file". Here you can import your Settings.json directly from the randomizer directory.

There are plenty of other advanced features that you might want to make use of and (most) of them are detailed in the usage doc. Let me know if you have any questions or run into any issues.
