### ISSUE TITLE
Issues with tracking spoiler log.

### ISSUE THREAD

**Issue by theCrimson247** [Thedrummonger/MMR-Tracker#11]
When importing my .html spoiler log into the tracker, all randomized items are incorrect. The spoiler log shows that I should get a mask from a chest, while the tracker thinks I should get a heart piece. The spoiler log is correct, while the tracker is not. I made sure that both the randomizer and the tracker are using casual randomization settings and both the spoiler log and the tracker are using the same "CustomItemListString". I have tried with multiple save files and .html spoiler logs and the results are the same; Incorrect randomization.
![83a3eb7068008d5ac51797d21a241dc8](https://user-images.githubusercontent.com/73251891/168450451-8724d3e3-b28e-4248-ad41-35501584639c.png)
![dd9ce16aea3752d9726e9d24cb31eca3](https://user-images.githubusercontent.com/73251891/168450453-c15f3cdf-0aaa-4705-b958-e9e3edd04da6.png)

**Comment by Thedrummonger** [comment]
This is an issue with newer beta version of the randomizer having different id's than the current stable release. When importing an html spoiler log or using the logic presets the tracker will use beta logic files from the MMR GitHub regardless of the version of the randomizer used to generate the spoiler log. The temporary workaround for this is to export your logic manually from the randomizer and use that when creating the tracker. 

This is what I assume to be the issue, but if it's not, this version of the tracker is now EOL and a rewritten version is available [here](https://github.com/Thedrummonger/MMR-Tracker-V3/releases) which fixes a number of common issues including this one. It does however only support randomizer version 1.15+ (currently the beta).
